version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fiap_p4a1_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: fiap_p4a1
      POSTGRES_PASSWORD: fiap_p4a1
      POSTGRES_DB: fiap_p4a1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: