[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"
[[chip]]
name = "npn-transistor"  # To use in the diagram.json, use "chip-npn-transistor" as the type
binary = "chips/npn-transistor.chip.wasm"